name: GCP Cert List
on:
 push:
   branches:
     - 'GCP'
   paths:
     - 'public/data-json/gcp-generate-cert-list.json'
 workflow_dispatch:

jobs:
  Merge-GCP-Report-Cert-List:
    runs-on: [ settings ]
    steps:
    - name: Clean workspace
      uses: albertsons/esgh-workspace-clean@v2-bash

    - name: Printing workspace cleaned message
      run: |
        echo "Workspace cleared for run ID ${{ github.run_number }}"
    - uses: actions/checkout@v3
      with: 
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Run Merge Script
      env:
         GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
          git clone --branch GCP https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.albertsons.com/albertsons/esgh-platform-dashboard.git
          cp esgh-platform-dashboard/public/data-json/gcp-generate-cert-list.json ${{ github.workspace }}/gcp-generate-cert-list.json
          cd esgh-platform-dashboard
          git checkout master
          cd ..
          #cp esgh-platform-dashboard/appowners_list.json ${{ github.workspace }}/appowners_list.json
          cp esgh-platform-dashboard/public/data-json/UserData.json ${{ github.workspace }}/UserData.json
          mv gcp-generate-cert-list.json gcp-generate-cert.json
          git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.albertsons.com/albertsons/esgh-organization-data.git
          cp esgh-organization-data/new_appowners_data.json ${{ github.workspace }}/new_appowners_data.json
          python gcp-generate-cert-list.py > gcp-generate-cert-list.json
          cd esgh-platform-dashboard
          cp ${{ github.workspace }}/gcp-generate-cert-list.json ./public/data-json/gcp-generate-cert-list.json
          git pull
          git add ./public/data-json/gcp-generate-cert-list.json
          git commit -m "GCP Cert Data" || true
          git push origin master
                    
    - name: Clean workspace
      if: always()
      uses: albertsons/esgh-workspace-clean@v2-bash

    - name: Printing workspace cleaned message
      run: |
        echo "Workspace cleared for run ID ${{ github.run_number }}"