name: Platform_DashBoard_oneclick_cd_workflow_prod
on:
  workflow_dispatch:
    inputs:
      prod:
        type: boolean
        description: 'deploy prod'
        required: false
        default: 'false'
      esghd-prod:
        type: boolean
        description: 'esghd-prod'
        required: false
        default: 'false'


jobs:
  prod-deploy:
    if: ${{ github.event.inputs.prod == 'true' }}
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-prod-autoschedule.yml@v5
    with:
      ENV_Name: ${{ needs.get_tag_name.outputs.deployment_environment }}
      deployment_environment: ${{ needs.get_tag_name.outputs.deployment_environment }}
      ACTIONSFILE: "Actionsfile/stage"
      TAG: ${{ github.ref_name }}
      REACT_APP_PRODUCTION: ${{ vars.REACT_APP_PRODUCTION }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
      REQUIRE_AUTH: ${{ vars.REQUIRE_AUTH_PROD }}
      AZ_CALLBACK_PATH: ${{ vars.AZ_CALLBACK_PATH }}
      ANNOUNCEMENT_URL: ${{ vars.REACT_APP_ANNOUNCEMENT_URL }}
      ORCH_API_ENDPOINT: ${{ vars.REACT_APP_ORCH_API_ENDPOINT_PROD }}
      SAML_ENV_PROPS_PATH: ${{ vars.SAML_ENV_PROPS_PATH }}
      REACT_SERVER_URL: ${{ vars.REACT_SERVER_URL_PROD }}
      REACT_APP_RUN_WORKFLOW_ENABLED: ${{ vars.REACT_APP_RUN_WORKFLOW_ENABLED_PROD }}
      KEYCLOAK_URL: ${{ vars.REACT_APP_KEYCLOAK_URL_PROD }}
      ACR_API_ENDPOINT: ${{ vars.REACT_APP_ACR_API_ENDPOINT_PROD }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_ISSUER: ${{ secrets.AZ_ISSUER_PROD }}
      AZ_CERT: ${{ secrets.AZ_CERT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ORCH_AUTH_TOKEN: ${{ secrets.REACT_APP_ORCH_AUTH_TOKEN }}
      ACR_API_KEY: ${{ secrets.REACT_APP_ACR_API_KEY }}
      KEYCLOAK_USERNAME: ${{ secrets.REACT_APP_KEYCLOAK_USERNAME_PROD }}
      KEYCLOAK_PASSWORD: ${{ secrets.REACT_APP_KEYCLOAK_PASSWORD_PROD }}
      ANNOUNCEMENT_API_KEY: ${{ secrets.ANNOUNCEMENT_API_KEY }}
  Deploy-Status-check-prod:
    needs: prod-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/stage"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  TRIGGER_EMAIL_WHEN_NEW_IMAGE_DEPLOYED_TO_PROD:
    if: ${{ needs.prod-deploy.result == 'success'}} || ${{ needs.prod-deploy.result == 'failure'}}
    needs: [ prod-deploy, Deploy-Status-check-prod ]
    name: TRIGGER_EMAIL_WHEN_NEW_IMAGE_DEPLOYED
    runs-on: [ settings ]
    steps:
      - name: action-send-mail
        uses: actions/checkout@v3
        with:
            repository: albertsons/esgh-action-mail
            ref: master
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            path: ./.github/albertsons/action-send-mail
      - uses: ./.github/albertsons/action-send-mail
        with:
          server_address: mailrouter.safeway.com
          server_port: 25
          subject: Platform Dashboard Prod Deployed with Image -${{ github.ref_name }} via ${{ github.workflow }}-${{ github.run_number }}-${{ needs.prod-deploy.result }}
          body: | 
            A new image -${{ github.ref_name }} deployed through workflow -${{ github.workflow }} with build numebr -${{ github.run_number }} on environment - prod
            is completed after succesfull deployed on dev1 environment thourth workflow ${{ github.workflow }} with build number - ${{ github.run_number }}
            Envirnoment: prod
            Branch: master
            Tag:${{ github.ref_name }}
            Workflow RUN Number: ${{ github.run_number }}
            Image: albertsons.azurecr.io/platform-dashboard:${{ needs.get_tag_name.outputs.TAG_NAME }} through workflow run - ${{ github.run_number }}
            GitHub Actor: ${{ github.actor }}
          to: Babak.Rahimi@albertsons.com,navachaitanya.kommoju@albertsons.com,rahul.bachhawat@albertsons.com,nivetha.velumani@albertsons.com,mateo.dejesusarbolea@albertsons.com,amena.afreen@albertsons.com,kristineerika.lunas@albertsons.com
          from: Platform.DevOps@albertsons.com

  esghd-prod-deploy:
    if: ${{ github.event.inputs.esghd-prod == 'true' }}
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-prod-autoschedule.yml@v5
    with:
      ENV_Name: ${{ needs.get_tag_name.outputs.deployment_environment }}
      deployment_environment: ${{ needs.get_tag_name.outputs.deployment_environment }}
      ACTIONSFILE: "Actionsfile/prod"
      TAG: ${{ github.ref_name }}
      REACT_APP_PRODUCTION: ${{ vars.REACT_APP_PRODUCTION }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
      REQUIRE_AUTH: ${{ vars.REQUIRE_AUTH_PROD }}
      AZ_CALLBACK_PATH: ${{ vars.AZ_CALLBACK_PATH }}
      ANNOUNCEMENT_URL: ${{ vars.REACT_APP_ANNOUNCEMENT_URL }}
      ORCH_API_ENDPOINT: ${{ vars.REACT_APP_ORCH_API_ENDPOINT_PROD }}
      SAML_ENV_PROPS_PATH: ${{ vars.SAML_ENV_PROPS_PATH }}
      REACT_SERVER_URL: ${{ vars.REACT_SERVER_URL_PROD }}
      REACT_APP_RUN_WORKFLOW_ENABLED: ${{ vars.REACT_APP_RUN_WORKFLOW_ENABLED_PROD }}
      KEYCLOAK_URL: ${{ vars.REACT_APP_KEYCLOAK_URL_PROD }}
      ACR_API_ENDPOINT: ${{ vars.REACT_APP_ACR_API_ENDPOINT_PROD }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_PROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_ISSUER: ${{ secrets.AZ_ISSUER_PROD }}
      AZ_CERT: ${{ secrets.AZ_CERT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ORCH_AUTH_TOKEN: ${{ secrets.REACT_APP_ORCH_AUTH_TOKEN }}
      ACR_API_KEY: ${{ secrets.REACT_APP_ACR_API_KEY }}
      KEYCLOAK_USERNAME: ${{ secrets.REACT_APP_KEYCLOAK_USERNAME_PROD }}
      KEYCLOAK_PASSWORD: ${{ secrets.REACT_APP_KEYCLOAK_PASSWORD_PROD }}
      ANNOUNCEMENT_API_KEY: ${{ secrets.ANNOUNCEMENT_API_KEY }}
  Deploy-Status-check-esghd-prod:
    needs: esghd-prod-deploy
    if: success()
    # if: success() && github.event.inputs.esghd-prod == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/prod"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_PROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  TRIGGER_EMAIL_WHEN_NEW_IMAGE_DEPLOYED_TO_ESGHD_PROD:
    if: ${{ needs.esghd-prod-deploy.result == 'success'}} || ${{ needs.esghd-prod-deploy.result == 'failure'}}
    needs: [ esghd-prod-deploy, Deploy-Status-check-esghd-prod ]
    name: TRIGGER_EMAIL_WHEN_NEW_IMAGE_DEPLOYED
    runs-on: [ settings ]
    steps:
      - name: action-send-mail
        uses: actions/checkout@v3
        with:
            repository: albertsons/esgh-action-mail
            ref: master
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            path: ./.github/albertsons/action-send-mail
      - uses: ./.github/albertsons/action-send-mail
        with:
          server_address: mailrouter.safeway.com
          server_port: 25
          subject: Platform Dashboard Prod Deployed with Image -${{ github.ref_name }} via ${{ github.workflow }}-${{ github.run_number }}-${{ needs.esghd-prod-deploy.result }}
          body: | 
            A new image -${{ github.ref_name }} deployed through workflow -${{ github.workflow }} with build numebr -${{ github.run_number }} on environment - prod
            is completed after succesfull deployed on dev1 environment thourth workflow ${{ github.workflow }} with build number - ${{ github.run_number }}
            Envirnoment: esghd-prod
            Branch: master
            Tag:${{ github.ref_name }}
            Workflow RUN Number: ${{ github.run_number }}
            Image: albertsons.azurecr.io/platform-dashboard:${{ needs.get_tag_name.outputs.TAG_NAME }} through workflow run - ${{ github.run_number }}
            GitHub Actor: ${{ github.actor }}
          to: Babak.Rahimi@albertsons.com,navachaitanya.kommoju@albertsons.com,rahul.bachhawat@albertsons.com,nivetha.velumani@albertsons.com,mateo.dejesusarbolea@albertsons.com,amena.afreen@albertsons.com,kristineerika.lunas@albertsons.com
          from: Platform.DevOps@albertsons.com