name: Platform_DashBoard_oneclick_cd_workflow_nonprod
on:
  workflow_dispatch:
    inputs:
      replicas:
        type: string  
        description: 'Replica count'
        required: false
        default: '1'
      dev1:
        type: boolean
        description: 'deploy dev1'
        required: false
        default: 'true'
      dev2:
        type: boolean
        description: 'deploy dev2'
        required: false
        default: 'true'
      dev3:
        type: boolean
        description: 'deploy dev3'
        required: false
        default: 'true'
      stage2:
        type: boolean
        description: 'deploy stage2'
        required: false
        default: 'true'

jobs:
  dev1-deploy:
    if: github.event.inputs.dev1 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod-autoschedule.yml@v5
    with:
      ENV_Name: dev1
      ACTIONSFILE: "Actionsfile/dev1"
      TAG: ${{ github.ref_name }}
      deployment_environment: dev1
      REACT_APP_PRODUCTION: ${{ vars.REACT_APP_PRODUCTION }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
      REQUIRE_AUTH: ${{ vars.REQUIRE_AUTH }}
      AZ_CALLBACK_PATH: ${{ vars.AZ_CALLBACK_PATH }}
      ANNOUNCEMENT_URL: ${{ vars.REACT_APP_ANNOUNCEMENT_URL }}
      ORCH_API_ENDPOINT: ${{ vars.REACT_APP_ORCH_API_ENDPOINT_NONPROD }}
      SAML_ENV_PROPS_PATH: ${{ vars.SAML_ENV_PROPS_PATH }}
      REACT_SERVER_URL: ""
      REACT_APP_RUN_WORKFLOW_ENABLED: ${{ vars.REACT_APP_RUN_WORKFLOW_ENABLED_NONPROD }}
      KEYCLOAK_URL: ${{ vars.REACT_APP_KEYCLOAK_URL_NONPROD_DEV }}
      ACR_API_ENDPOINT: ${{ vars.REACT_APP_ACR_API_ENDPOINT_NONPROD }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_ISSUER: ${{ secrets.AZ_ISSUER_NONPROD }}
      AZ_CERT: ${{ secrets.AZ_CERT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ORCH_AUTH_TOKEN: ${{ secrets.REACT_APP_ORCH_AUTH_TOKEN }}
      ACR_API_KEY: ${{ secrets.REACT_APP_ACR_API_KEY }}
      KEYCLOAK_USERNAME: ${{ secrets.REACT_APP_KEYCLOAK_USERNAME_NONPROD }}
      KEYCLOAK_PASSWORD: ${{ secrets.REACT_APP_KEYCLOAK_PASSWORD_NONPROD }}
      ANNOUNCEMENT_API_KEY: ${{ secrets.ANNOUNCEMENT_API_KEY }}
  Deploy-Status-check-dev1:
    needs: dev1-deploy
    if: success() && github.event.inputs.dev1 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/dev1"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  dev2-deploy:
    if: github.event.inputs.dev2 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod-autoschedule.yml@v5
    with:
      ENV_Name: dev2
      ACTIONSFILE: "Actionsfile/dev2"
      TAG: ${{ github.ref_name }}
      deployment_environment: dev2
      REACT_APP_PRODUCTION: ${{ vars.REACT_APP_PRODUCTION }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
      REQUIRE_AUTH: ${{ vars.REQUIRE_AUTH }}
      AZ_CALLBACK_PATH: ${{ vars.AZ_CALLBACK_PATH }}
      ANNOUNCEMENT_URL: ${{ vars.REACT_APP_ANNOUNCEMENT_URL }}
      ORCH_API_ENDPOINT: ${{ vars.REACT_APP_ORCH_API_ENDPOINT_NONPROD }}
      SAML_ENV_PROPS_PATH: ${{ vars.SAML_ENV_PROPS_PATH }}
      REACT_SERVER_URL: ""
      REACT_APP_RUN_WORKFLOW_ENABLED: ${{ vars.REACT_APP_RUN_WORKFLOW_ENABLED }}
      KEYCLOAK_URL: ${{ vars.REACT_APP_KEYCLOAK_URL_NONPROD_DEV }}
      ACR_API_ENDPOINT: ${{ vars.REACT_APP_ACR_API_ENDPOINT_NONPROD }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_ISSUER: ${{ secrets.AZ_ISSUER_NONPROD }}
      AZ_CERT: ${{ secrets.AZ_CERT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ORCH_AUTH_TOKEN: ${{ secrets.REACT_APP_ORCH_AUTH_TOKEN }}
      ACR_API_KEY: ${{ secrets.REACT_APP_ACR_API_KEY }}
      KEYCLOAK_USERNAME: ${{ secrets.REACT_APP_KEYCLOAK_USERNAME_NONPROD }}
      KEYCLOAK_PASSWORD: ${{ secrets.REACT_APP_KEYCLOAK_PASSWORD_NONPROD }}
      ANNOUNCEMENT_API_KEY: ${{ secrets.ANNOUNCEMENT_API_KEY }}
  Deploy-Status-check-dev2:
    needs: dev2-deploy
    if: success() && github.event.inputs.dev2 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/dev2"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  dev3-deploy:
    if: github.event.inputs.dev3 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod-autoschedule.yml@v5
    with:
      ENV_Name: dev3
      ACTIONSFILE: "Actionsfile/dev3"
      TAG: ${{ github.ref_name }}
      deployment_environment: dev3
      REACT_APP_PRODUCTION: ${{ vars.REACT_APP_PRODUCTION }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
      REQUIRE_AUTH: ${{ vars.REQUIRE_AUTH }}
      AZ_CALLBACK_PATH: ${{ vars.AZ_CALLBACK_PATH }}
      ANNOUNCEMENT_URL: ${{ vars.REACT_APP_ANNOUNCEMENT_URL }}
      ORCH_API_ENDPOINT: ${{ vars.REACT_APP_ORCH_API_ENDPOINT_NONPROD }}
      SAML_ENV_PROPS_PATH: ${{ vars.SAML_ENV_PROPS_PATH }}
      REACT_SERVER_URL: ""
      REACT_APP_RUN_WORKFLOW_ENABLED: ${{ vars.REACT_APP_RUN_WORKFLOW_ENABLED }}
      KEYCLOAK_URL: ${{ vars.REACT_APP_KEYCLOAK_URL_NONPROD_DEV }}
      ACR_API_ENDPOINT: ${{ vars.REACT_APP_ACR_API_ENDPOINT_NONPROD }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_ISSUER: ${{ secrets.AZ_ISSUER_NONPROD }}
      AZ_CERT: ${{ secrets.AZ_CERT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ORCH_AUTH_TOKEN: ${{ secrets.REACT_APP_ORCH_AUTH_TOKEN }}
      ACR_API_KEY: ${{ secrets.REACT_APP_ACR_API_KEY }}
      KEYCLOAK_USERNAME: ${{ secrets.REACT_APP_KEYCLOAK_USERNAME_NONPROD }}
      KEYCLOAK_PASSWORD: ${{ secrets.REACT_APP_KEYCLOAK_PASSWORD_NONPROD }}
      ANNOUNCEMENT_API_KEY: ${{ secrets.ANNOUNCEMENT_API_KEY }}
  Deploy-Status-check-dev3:
    needs: dev3-deploy
    if: success() && github.event.inputs.dev3 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/dev3"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  stage2-deploy:
    if: github.event.inputs.stage2 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod-autoschedule.yml@v5
    with:
      ENV_Name: stage2
      ACTIONSFILE: "Actionsfile/stage2"
      TAG: ${{ github.ref_name }}
      deployment_environment: stage2
      REACT_APP_PRODUCTION: ${{ vars.REACT_APP_PRODUCTION }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
      REQUIRE_AUTH: ${{ vars.REQUIRE_AUTH_NONPROD }}
      AZ_CALLBACK_PATH: ${{ vars.AZ_CALLBACK_PATH }}
      ANNOUNCEMENT_URL: ${{ vars.REACT_APP_ANNOUNCEMENT_URL }}
      ORCH_API_ENDPOINT: ${{ vars.REACT_APP_ORCH_API_ENDPOINT_NONPROD }}
      SAML_ENV_PROPS_PATH: ${{ vars.SAML_ENV_PROPS_PATH }}
      REACT_SERVER_URL: ${{ vars.REACT_SERVER_URL }}
      REACT_APP_RUN_WORKFLOW_ENABLED: ${{ vars.REACT_APP_RUN_WORKFLOW_ENABLED }}
      KEYCLOAK_URL: ${{ vars.REACT_APP_KEYCLOAK_URL_NONPROD_STAGE }}
      ACR_API_ENDPOINT: ${{ vars.REACT_APP_ACR_API_ENDPOINT_NONPROD }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZ_ISSUER: ${{ secrets.AZ_ISSUER_NONPROD }}
      AZ_CERT: ${{ secrets.AZ_CERT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ORCH_AUTH_TOKEN: ${{ secrets.REACT_APP_ORCH_AUTH_TOKEN }}
      ACR_API_KEY: ${{ secrets.REACT_APP_ACR_API_KEY }}
      KEYCLOAK_USERNAME: ${{ secrets.REACT_APP_KEYCLOAK_USERNAME_NONPROD }}
      KEYCLOAK_PASSWORD: ${{ secrets.REACT_APP_KEYCLOAK_PASSWORD_NONPROD }}
      ANNOUNCEMENT_API_KEY: ${{ secrets.ANNOUNCEMENT_API_KEY }}
  Deploy-Status-check-stage2:
    needs: stage2-deploy
    if: success() && github.event.inputs.stage2 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/stage2"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}