name: Update Monthly Workflow Runs Count
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 9 1 * *'
        
jobs:
  Get-StartEnddates:
      runs-on: [ Portal ]
      outputs:
        EndDate: ${{ steps.getDates.outputs.EndDate }}
        StartDate: ${{ steps.getDates.outputs.StartDate }}
      steps:
      - name: Get start and end dates
        id: getDates
        shell: pwsh
        run: |
            $EndDate = (Get-Date -Day 1).AddDays(-1).ToString("yyyy-MM-dd")
            $EndDate = $EndDate -replace " ", ""
            echo "::set-output name=EndDate::$EndDate"
            $StartDate = (Get-Date -Day 1).AddMonths(-1).ToString("yyyy-MM-dd")
            $StartDate = $StartDate -replace " ", ""
            echo "::set-output name=StartDate::$StartDate"
  
  Totalcount-Script:
      needs: Get-StartEnddates
      uses: albertsons/esgh-platform-dashboard/.github/workflows/workflow-totalcount.yml@master
      with:
        StartDate: ${{ needs.Get-StartEnddates.outputs.StartDate }}
        EndDate: ${{ needs.Get-StartEnddates.outputs.EndDate }}
      secrets:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  UpdateJSFile-Commit:
      runs-on: [ Portal ]
      needs: Totalcount-Script
      steps:
      - name: Update JS file
        shell: pwsh
        run: |
            $file = './src/data/historyWorkflow.js'
            $content = Get-Content $file
            $content = $content -replace "export const HistoryCount = ", ""
            $content = $content | ConvertFrom-Json
            $PrevMonth = (Get-Date). AddMonths(-1). ToString('MM')
            $CurrentYear = (Get-Date). AddMonths(-1). ToString('yy')
            $totalCount = ${{ needs.Totalcount-Script.outputs.totalCount }}
            $PrevMonthData = @"
            {
              "Month": "$PrevMonth/$CurrentYear",
              "Count": "$totalCount"
            }
            "@
            $content.data += (ConvertFrom-Json -InputObject $PrevMonthData)
            $content = $content | ConvertTo-Json
            $Opening = "export const HistoryCount = [`n"
            $Closing = "`n]"
            $content = $Opening + $Content + $Closing
            $content > ./src/data/historyWorkflow.js
      - name: commit change
        continue-on-error: true
        run: |
          git add .
          git commit -m "${{ github.workflow }}-${{ github.run_number }}"
          git pull --set-upstream https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.albertsons.com/${{ github.repository }} --rebase master
          git push --set-upstream https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.albertsons.com/${{ github.repository }} master